exception DivByZero;
def main() {
    try {
        print(1);
    } except DivByZero {
        print(42);
    } except DivByZero {
        print(43);
    }
}
