exception DivByZero;
def main() {
    try {
        print(1);
    } except UndeclaredException {
        print(42);
    }
}
